/*
FILE PURPOSE:
This page renders advanced Data Science visualisations (Confusion Matrices, ROC curves) 
using standard React elements (Divs and SVGs) without relying on heavy chart libraries.

FLOW:
1. Loads evaluation data generated by our Python training scripts.
2. Allows the user to toggle between different trained models via a tab bar.
3. Renders dataset statistics (Train/Test split).
4. Renders 4 high-level metric gauges (Accuracy, Precision, Recall, F1).
5. Draws a dynamic Heatmap (Confusion Matrix) to show where the model is making mistakes.
6. Draws a mathematical ROC Curve to show the trade-off between True Positives and False Positives.

WHY THIS EXISTS:
Real-world machine learning models are evaluated using complex matrices and curves, not just a single
"95% accuracy" number. This component provides academic-level transparency into the model's flaws.
*/

import React, { useState, useEffect } from "react";
import { Database, Grid2x2, TrendingUp, List, Settings } from "lucide-react";

export default function ModelEvaluation() {
  const [data, setData] = useState(null);
  
  // Which model's overall data is currently being viewed
  const [selectedModel, setSelectedModel] = useState("binary_mlp");
  
  // Which model's confusion matrix is being viewed (can be toggled separately)
  const [cmView, setCmView] = useState("binary_mlp");

  useEffect(() => {
    fetch("/evaluation_results.json")
      .then((res) => res.json())
      .then(setData)
      .catch((err) => console.error("Failed to load evaluation data:", err));
  }, []);

  if (!data) {
    return (
      <div className="eval-loading">
        <div className="spinner" style={{ width: 24, height: 24, borderWidth: 3 }} />
        <p>Loading evaluation data…</p>
      </div>
    );
  }

  const { dataset, models } = data;
  const model = models[selectedModel];
  const cmModel = models[cmView];

  return (
    <div className="eval-page">
      {/* Page Header */}
      <section className="intro" style={{ animationDelay: "0s" }}>
        <p className="intro-tag">Auxiliary signal · not the final verdict</p>
        <h2 className="intro-heading">Model Evaluation</h2>
        <p className="intro-desc">
          These metrics document the legacy training prototype only. The production system
          uses a claim-aware search, evidence filtering, and NLI/stance analysis pipeline.
          The historical MLP remains visible as a weak prior, but it never determines the final
          verdict when evidence is insufficient or conflicting.
        </p>
      </section>

      {/* Dataset Overview */}
      <div className="eval-dataset-card" id="dataset-overview">
        <h3 className="eval-section-title">
          <Database className="eval-icon" size={20} /> Dataset: {dataset.name}
        </h3>
        <div className="eval-dataset-grid">
          <div className="eval-dataset-stat">
            <span className="eval-stat-number">{dataset.train_size.toLocaleString()}</span>
            <span className="eval-stat-label">Training</span>
          </div>
          <div className="eval-dataset-stat">
            <span className="eval-stat-number">{dataset.valid_size.toLocaleString()}</span>
            <span className="eval-stat-label">Validation</span>
          </div>
          <div className="eval-dataset-stat">
            <span className="eval-stat-number">{dataset.test_size.toLocaleString()}</span>
            <span className="eval-stat-label">Test</span>
          </div>
        </div>
        <div className="eval-label-dist">
          <p className="eval-label-dist-title">Test set label distribution:</p>
          <div className="eval-label-bars">
            {dataset.labels_6class.map((label) => {
              const count = dataset.label_distribution[label] || 0;
              const pct = ((count / dataset.test_size) * 100).toFixed(1);
              return (
                <div className="eval-label-bar-row" key={label}>
                  <span className="eval-label-name">{label}</span>
                  <div className="eval-label-bar-track">
                    <div
                      className="eval-label-bar-fill"
                      style={{ width: `${pct}%` }}
                    />
                  </div>
                  <span className="eval-label-count">{count} ({pct}%)</span>
                </div>
              );
            })}
          </div>
        </div>
        <p className="eval-binary-note">{dataset.binary_mapping}</p>
      </div>

      {/* Model Selector Tab Bar */}
      <div className="eval-model-selector" id="model-selector">
        {Object.entries(models).map(([key, m]) => (
          <button
            key={key}
            className={`eval-model-tab ${selectedModel === key ? "active" : ""}`}
            onClick={() => setSelectedModel(key)}
          >
            {m.name}
            {/* Not "IN USE": this model ships, but as an advisory prior that
                the verdict never reads. Badging it "IN USE" next to a 56.9%
                accuracy invites the reading that the fact-checker is 57%
                accurate — and contradicts what every other screen says. */}
            {m.is_production && <span className="eval-prod-badge">SHIPPED AS PRIOR</span>}
          </button>
        ))}
      </div>

      {/* Metrics Dashboard */}
      <div className="eval-metrics-grid" id="metrics-dashboard">
        <MetricCard label="Accuracy" value={model.accuracy} color="var(--purple)" />
        <MetricCard label="Precision" value={model.precision} color="var(--blue)" />
        <MetricCard label="Recall" value={model.recall} color="var(--green)" />
        <MetricCard label="F1 Score" value={model.f1} color="var(--amber)" />
      </div>

      {/* Accuracy against the baseline anyone would compute themselves.
          Stating this is the whole reason the architecture is evidence-first,
          and leaving the reader to discover it is worse than owning it. */}
      <BaselineComparison dataset={dataset} model={model} />

      {/* Confusion Matrix + ROC side by side */}
      <div className="eval-charts-row">
        
        {/* Confusion Matrix */}
        <div className="eval-chart-card" id="confusion-matrix">
          <div className="eval-chart-header">
            <h3 className="eval-section-title">
              <Grid2x2 className="eval-icon" size={20} /> Confusion Matrix
            </h3>
            <div className="eval-cm-toggle">
              {Object.entries(models).map(([key]) => (
                <button
                  key={key}
                  className={`eval-cm-btn ${cmView === key ? "active" : ""}`}
                  onClick={() => setCmView(key)}
                >
                  {key === "binary_mlp" ? "Binary MLP" : key === "logistic_regression" ? "Log. Reg." : "6-Class"}
                </button>
              ))}
            </div>
          </div>
          <ConfusionMatrix
            matrix={cmModel.confusion_matrix}
            labels={cmModel.labels}
          />
        </div>

        {/* ROC Curve */}
        {model.roc_curve && (
          <div className="eval-chart-card" id="roc-curve">
            <h3 className="eval-section-title">
              <TrendingUp className="eval-icon" size={20} /> ROC Curve
              <span className="eval-auc-badge">AUC = {model.auc}</span>
            </h3>
            <ROCCurve points={model.roc_curve} />
            {model.threshold && (
              <p className="eval-threshold-note">
                Decision threshold: <strong>{model.threshold}</strong>
                {model.is_production && " (tuned on validation set)"}
              </p>
            )}
          </div>
        )}
      </div>

      {/* Per-class metrics for 6-class models */}
      {model.per_class_metrics && (
        <div className="eval-chart-card eval-full-width" id="per-class-metrics">
          <h3 className="eval-section-title">
            <List className="eval-icon" size={20} /> Per-Class Metrics
          </h3>
          <div className="eval-per-class-table">
            <div className="eval-pc-header">
              <span>Label</span>
              <span>Precision</span>
              <span>Recall</span>
              <span>F1</span>
              <span>Support</span>
            </div>
            {model.per_class_metrics.map((m, i) => (
              <div className="eval-pc-row" key={i} style={{ animationDelay: `${i * 0.05}s` }}>
                <span className="eval-pc-label">{model.labels[i]}</span>
                <span><BarValue value={m.precision} color="var(--blue)" /></span>
                <span><BarValue value={m.recall} color="var(--green)" /></span>
                <span><BarValue value={m.f1} color="var(--amber)" /></span>
                <span className="eval-pc-support">{m.support}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Model details */}
      <div className="eval-chart-card eval-full-width" id="model-details">
        <h3 className="eval-section-title">
          <Settings className="eval-icon" size={20} /> Model Details — {model.name}
        </h3>
        <div className="eval-details-grid">
          <div className="eval-detail-item">
            <span className="eval-detail-label">Architecture</span>
            <span className="eval-detail-value">{model.architecture}</span>
          </div>
          <div className="eval-detail-item">
            <span className="eval-detail-label">Input Features</span>
            <span className="eval-detail-value">{model.input_features}</span>
          </div>
          <div className="eval-detail-item">
            <span className="eval-detail-label">Training</span>
            <span className="eval-detail-value">{model.training}</span>
          </div>
          <div className="eval-detail-item">
            <span className="eval-detail-label">Output Classes</span>
            <span className="eval-detail-value">{model.classes}</span>
          </div>
        </div>
      </div>
    </div>
  );
}


// ─── Sub-components ──────────────────────────────────────────────────

/*
PURPOSE: Put an accuracy number next to the score you would get by guessing.

WHY THIS EXISTS:
An accuracy figure means nothing without the majority-class baseline beside
it. On this test set 56.4% of examples fall in the larger binary class, so a
model that always answered "true" would score 56.4%. Reporting 56.9% without
that comparison invites the reader to think the model works — and reporting it
on a fact-checking site invites them to think the SYSTEM is 57% accurate.

It is neither. That is precisely why the verdict pipeline is evidence-based
and does not read this model's output at all. Saying so plainly is a stronger
position than letting a reader compute the baseline themselves and wonder
whether anyone noticed.
*/
function BaselineComparison({ dataset, model }) {
  const distribution = dataset.label_distribution || {};
  const falseish = ["pants-fire", "false", "barely-true"]
    .reduce((sum, label) => sum + (distribution[label] || 0), 0);
  const trueish = dataset.test_size - falseish;
  const baseline = Math.max(falseish, trueish) / dataset.test_size;

  // Only meaningful for the binary task; the 6-class model has its own baseline.
  if (!model.is_production || !dataset.test_size) return null;

  const delta = (model.accuracy - baseline) * 100;
  const beatsBaseline = delta > 0;

  return (
    <div className="eval-baseline-card" id="baseline-comparison">
      <div className="eval-baseline-row">
        <span className="eval-baseline-label">Model accuracy</span>
        <span className="eval-baseline-value">{(model.accuracy * 100).toFixed(1)}%</span>
      </div>
      <div className="eval-baseline-row">
        <span className="eval-baseline-label">
          Always guessing the larger class
        </span>
        <span className="eval-baseline-value">{(baseline * 100).toFixed(1)}%</span>
      </div>
      <p className="eval-baseline-note">
        A difference of <strong>{beatsBaseline ? "+" : ""}{delta.toFixed(1)} points</strong>.
        On text alone, without evidence, telling true claims from false ones is
        close to a coin flip — which is exactly why the verdict is computed from
        retrieved evidence and never reads this model&apos;s output.
      </p>
    </div>
  );
}

/*
PURPOSE: Draws a small circular progress bar for individual metrics (Accuracy, F1, etc).
*/
function MetricCard({ label, value, color }) {
  const pct = Math.round(value * 100);
  const radius = 40;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (value * circumference);

  return (
    <div className="eval-metric-card">
      <div className="eval-metric-gauge">
        <svg viewBox="0 0 100 100" className="eval-metric-svg">
          <circle cx="50" cy="50" r={radius} className="eval-metric-bg" />
          <circle
            cx="50" cy="50" r={radius}
            className="eval-metric-fill"
            style={{
              stroke: color,
              strokeDasharray: circumference,
              strokeDashoffset: offset,
            }}
          />
        </svg>
        <span className="eval-metric-number" style={{ color }}>{pct}%</span>
      </div>
      <span className="eval-metric-label">{label}</span>
    </div>
  );
}

/*
PURPOSE: Draws a Data Science "Confusion Matrix" heatmap.
WHY THIS EXISTS: Helps us see if the model frequently mistakes "Mostly True" for "Half True".
*/
function ConfusionMatrix({ matrix, labels }) {
  const maxVal = Math.max(...matrix.flat());
  const total = matrix.flat().reduce((a, b) => a + b, 0);
  const isLarge = labels.length > 2;

  return (
    <div className={`eval-cm ${isLarge ? "eval-cm-large" : ""}`}>
      {/* Column headers */}
      <div className="eval-cm-corner">
        <span className="eval-cm-axis-label eval-cm-axis-pred">Predicted →</span>
        <span className="eval-cm-axis-label eval-cm-axis-actual">Actual ↓</span>
      </div>
      {labels.map((l) => (
        <div className="eval-cm-col-label" key={`col-${l}`}>
          {isLarge ? l.replace("barely-", "b-").replace("mostly-", "m-").replace("pants-fire", "p-fire") : l}
        </div>
      ))}
      
      {/* Heatmap Grid */}
      {matrix.map((row, i) => (
        <React.Fragment key={`row-${i}`}>
          <div className="eval-cm-row-label">
            {isLarge ? labels[i].replace("barely-", "b-").replace("mostly-", "m-").replace("pants-fire", "p-fire") : labels[i]}
          </div>
          {row.map((val, j) => {
            // Calculate opacity based on how large the number is compared to the maximum cell
            const intensity = maxVal > 0 ? val / maxVal : 0;
            const isDiag = i === j; // The diagonal represents correct predictions
            const pct = total > 0 ? ((val / total) * 100).toFixed(1) : "0";
            return (
              <div
                className={`eval-cm-cell ${isDiag ? "eval-cm-diag" : ""}`}
                key={`${i}-${j}`}
                style={{
                  "--intensity": intensity,
                  backgroundColor: isDiag
                    ? `rgba(124, 58, 237, ${0.1 + intensity * 0.55})` // Purple for correct
                    : `rgba(220, 38, 38, ${intensity * 0.35})`,       // Red for incorrect
                }}
                title={`Actual: ${labels[i]}, Predicted: ${labels[j]}\n${val} samples (${pct}%)`}
              >
                <span className="eval-cm-val">{val}</span>
                <span className="eval-cm-pct">{pct}%</span>
              </div>
            );
          })}
        </React.Fragment>
      ))}
    </div>
  );
}

/*
PURPOSE: Manually draws an ROC (Receiver Operating Characteristic) curve using SVG paths.
WHY THIS EXISTS: ROC curves show if the model is better than random guessing (the diagonal line).
*/
function ROCCurve({ points }) {
  const width = 300;
  const height = 300;
  const pad = 40;
  const innerW = width - pad * 2;
  const innerH = height - pad * 2;

  // Convert math coordinates (0-1) to pixel coordinates (0-300)
  const toX = (fpr) => pad + fpr * innerW;
  const toY = (tpr) => pad + (1 - tpr) * innerH;

  const polyline = points
    .map((p) => `${toX(p.fpr)},${toY(p.tpr)}`)
    .join(" ");

  // The shaded area under the line
  const areaPath = `M ${toX(0)},${toY(0)} ` +
    points.map((p) => `L ${toX(p.fpr)},${toY(p.tpr)}`).join(" ") +
    ` L ${toX(points[points.length - 1]?.fpr || 1)},${toY(0)} Z`;

  return (
    <div className="eval-roc-container">
      <svg viewBox={`0 0 ${width} ${height}`} className="eval-roc-svg">
        {/* Grid lines */}
        {[0.25, 0.5, 0.75].map((v) => (
          <g key={v}>
            <line x1={toX(v)} y1={toY(0)} x2={toX(v)} y2={toY(1)} className="eval-roc-grid" />
            <line x1={toX(0)} y1={toY(v)} x2={toX(1)} y2={toY(v)} className="eval-roc-grid" />
          </g>
        ))}

        {/* Baseline diagonal (random guessing) */}
        <line
          x1={toX(0)} y1={toY(0)}
          x2={toX(1)} y2={toY(1)}
          className="eval-roc-baseline"
        />
        <text x={toX(0.62)} y={toY(0.55)} className="eval-roc-baseline-label">Random</text>

        {/* Area under curve */}
        <path d={areaPath} className="eval-roc-area" />

        {/* The actual ROC Line */}
        <polyline points={polyline} className="eval-roc-line" />

        {/* Axes */}
        <line x1={toX(0)} y1={toY(0)} x2={toX(1)} y2={toY(0)} className="eval-roc-axis" />
        <line x1={toX(0)} y1={toY(0)} x2={toX(0)} y2={toY(1)} className="eval-roc-axis" />

        {/* Axis labels */}
        <text x={toX(0.5)} y={height - 4} className="eval-roc-axis-text" textAnchor="middle">
          False Positive Rate
        </text>
        <text x={8} y={toY(0.5)} className="eval-roc-axis-text" textAnchor="middle"
          transform={`rotate(-90, 8, ${toY(0.5)})`}>
          True Positive Rate
        </text>

        {/* Tick labels */}
        {[0, 0.25, 0.5, 0.75, 1].map((v) => (
          <g key={`tick-${v}`}>
            <text x={toX(v)} y={toY(0) + 14} className="eval-roc-tick" textAnchor="middle">{v}</text>
            <text x={toX(0) - 6} y={toY(v) + 4} className="eval-roc-tick" textAnchor="end">{v}</text>
          </g>
        ))}
      </svg>
    </div>
  );
}

function BarValue({ value, color }) {
  const pct = Math.round(value * 100);
  return (
    <div className="eval-bar-value">
      <div className="eval-bar-track">
        <div className="eval-bar-fill" style={{ width: `${pct}%`, background: color }} />
      </div>
      <span className="eval-bar-num">{pct}%</span>
    </div>
  );
}
