/*
FILE PURPOSE:
This page displays a side-by-side comparison of three different ML architectures tested for this project:
Logistic Regression, a 6-Class MLP, and the final production Binary Truth MLP.

FLOW:
1. Fetches pre-computed evaluation data from a local JSON file (`evaluation_results.json`).
2. Renders a summary "Winner" banner showing how much better the chosen model is.
3. Renders a detailed HTML table comparing Accuracy, Precision, Recall, and Architecture.
4. Renders a 4-card grid explaining *why* the Binary MLP was chosen over the others.

WHY THIS EXISTS:
In an educational or portfolio project, it's not enough to just show the final working product. 
You must prove *why* you made certain engineering decisions over others.
*/

import { useState, useEffect } from "react";
import { Trophy, Target, FlaskConical, Activity, Scale, Lightbulb, Brain, Settings2, Link, Spline } from "lucide-react";

export default function ModelComparison() {
  const [data, setData] = useState(null);

  // Fetch the pre-computed evaluation results generated by our Python training scripts.
  useEffect(() => {
    fetch("/evaluation_results.json")
      .then((res) => res.json())
      .then(setData)
      .catch((err) => console.error("Failed to load evaluation data:", err));
  }, []);

  if (!data) {
    return (
      <div className="eval-loading">
        <div className="spinner" style={{ width: 24, height: 24, borderWidth: 3 }} />
        <p>Loading comparison data…</p>
      </div>
    );
  }

  const { models } = data;
  const lr = models.logistic_regression;
  const mlp6 = models.mlp_6class;
  const bt = models.binary_mlp;

  // Helper function to format the difference between two numbers (e.g., "+4.2")
  const delta = (a, b) => {
    const diff = ((a - b) * 100).toFixed(1);
    return diff > 0 ? `+${diff}` : diff;
  };

  const metricsRows = [
    {
      label: "Accuracy",
      lr: lr.accuracy,
      mlp6: mlp6.accuracy,
      bt: bt.accuracy,
      icon: <Target size={16} />,
    },
    {
      label: "Precision",
      lr: lr.precision,
      mlp6: mlp6.precision,
      bt: bt.precision,
      icon: <FlaskConical size={16} />,
    },
    {
      label: "Recall",
      lr: lr.recall,
      mlp6: mlp6.recall,
      bt: bt.recall,
      icon: <Activity size={16} />,
    },
    {
      label: "F1 Score",
      lr: lr.f1,
      mlp6: mlp6.f1,
      bt: bt.f1,
      icon: <Scale size={16} />,
    },
  ];

  const detailRows = [
    { label: "Architecture", lr: lr.architecture, mlp6: mlp6.architecture, bt: bt.architecture },
    { label: "Input Features", lr: lr.input_features, mlp6: mlp6.input_features, bt: bt.input_features },
    { label: "Training", lr: lr.training, mlp6: mlp6.training, bt: bt.training },
    { label: "Output Classes", lr: lr.classes, mlp6: mlp6.classes, bt: bt.classes },
  ];

  return (
    <div className="comp-page">
      <section className="intro" style={{ animationDelay: "0s" }}>
        <p className="intro-tag">Auxiliary research · final verdict is evidence-first</p>
        <h2 className="intro-heading">Model Comparison</h2>
        <p className="intro-desc">
          These are historical prototype results from a training exercise. The final product
          does not rely on any one model score to determine truth; it filters evidence,
          checks source quality, and uses NLI to evaluate the proposition directly.
        </p>
      </section>

      {/* Historical note */}
      <div className="comp-winner-banner" id="winner-banner">
        <div className="comp-winner-icon"><Trophy size={28} color="var(--purple)" /></div>
        <div className="comp-winner-text">
          <strong>Legacy model signal</strong> remains visible for research context, but
          it is kept as a weak prior and never replaces the evidence-first verdict.
        </div>
      </div>

      {/* Comparison Table */}
      <div className="comp-table-wrapper" id="comparison-table">
        <table className="comp-table">
          <thead>
            <tr>
              <th className="comp-th-metric">Metric</th>
              <th className="comp-th-model">
                <span className="comp-model-name">Logistic Regression</span>
                <span className="comp-model-sub">Baseline</span>
              </th>
              <th className="comp-th-model">
                <span className="comp-model-name">MLP 6-Class</span>
                <span className="comp-model-sub">Fine-grained</span>
              </th>
              <th className="comp-th-model comp-th-winner">
                <span className="comp-model-name" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.3rem' }}>
                  Historical Binary MLP
                  <span className="comp-star" style={{ display: 'flex' }}><Trophy size={14} /></span>
                </span>
                <span className="comp-model-sub">Auxiliary</span>
              </th>
            </tr>
          </thead>
          <tbody>
            {/* Metric rows */}
            {metricsRows.map((row, i) => {
              const values = [row.lr, row.mlp6, row.bt];
              const best = Math.max(...values); // Highlight the column with the highest score

              return (
                <tr key={row.label} className="comp-metric-row" style={{ animationDelay: `${i * 0.06}s` }}>
                  <td className="comp-td-label">
                    <span className="comp-row-icon">{row.icon}</span>
                    {row.label}
                  </td>
                  {[row.lr, row.mlp6, row.bt].map((val, j) => (
                    <td
                      key={j}
                      className={`comp-td-value ${val === best ? "comp-td-best" : ""} ${j === 2 ? "comp-td-winner-col" : ""}`}
                    >
                      <span className="comp-value">{(val * 100).toFixed(1)}%</span>
                      {j > 0 && (
                        <span className={`comp-delta ${val >= row.lr ? "comp-delta-up" : "comp-delta-down"}`}>
                          {val >= row.lr ? "↑" : "↓"} {Math.abs(((val - row.lr) * 100)).toFixed(1)}%
                        </span>
                      )}
                      {val === best && <span className="comp-best-dot" />}
                    </td>
                  ))}
                </tr>
              );
            })}

            {/* Separator */}
            <tr className="comp-separator">
              <td colSpan={4}><div className="comp-sep-line" /></td>
            </tr>

            {/* Detail rows */}
            {detailRows.map((row, i) => (
              <tr key={row.label} className="comp-detail-row" style={{ animationDelay: `${(metricsRows.length + i) * 0.06}s` }}>
                <td className="comp-td-label comp-td-label-detail">{row.label}</td>
                <td className="comp-td-detail">{row.lr}</td>
                <td className="comp-td-detail">{row.mlp6}</td>
                <td className="comp-td-detail comp-td-winner-col">{row.bt}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Historical model note */}
      <div className="comp-why-card" id="why-binary-mlp">
        <h3 className="eval-section-title">
          <Lightbulb className="eval-icon" size={20} /> Why the legacy model remains auxiliary
        </h3>
        <div className="comp-why-grid">
          <div className="comp-why-item">
            <div className="comp-why-icon"><Brain size={24} color="var(--purple)" /></div>
            <h4>Research context</h4>
            <p>
              The model comparison is useful as a historical prototype, but it does not represent the
              final production decision engine. The live checker is evidence-first.
            </p>
          </div>
          <div className="comp-why-item">
            <div className="comp-why-icon"><Settings2 size={24} color="var(--purple)" /></div>
            <h4>Low-weight prior</h4>
            <p>
              The learned score can still be shown for transparency, but it is treated as a weak prior
              and never overrides strong search, passage-level, or NLI evidence.
            </p>
          </div>
          <div className="comp-why-item">
            <div className="comp-why-icon"><Link size={24} color="var(--purple)" /></div>
            <h4>Evidence integration</h4>
            <p>
              The production verdict depends primarily on the same claim, retrieved evidence, source quality,
              contradiction checks, and NLI-supported support or contradiction.
            </p>
          </div>
          <div className="comp-why-item">
            <div className="comp-why-icon"><Spline size={24} color="var(--purple)" /></div>
            <h4>Abstention when uncertain</h4>
            <p>
              When evidence is weak, absent, or conflicting, the system abstains instead of forcing an
              overconfident truth label.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
